# Generated by Django 2.2 on 2019-04-06 22:49

import bitfield.models
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('дата создания', models.DateTimeField(auto_now_add=True)),
                ('дата изменения', models.DateTimeField(auto_now=True)),
                ('plomb_id', models.CharField(default='', max_length=255, unique=True)),
                ('barcode', models.CharField(default='', max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('дата создания', models.DateTimeField(auto_now_add=True)),
                ('дата изменения', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Рейс',
                'verbose_name_plural': 'Рейсы',
            },
        ),
        migrations.CreateModel(
            name='SystemUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('flags', bitfield.models.BitField((('board_conductor', '0'), ('deliveryman', '1')), default=None)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ServiceClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('дата создания', models.DateTimeField(auto_now_add=True)),
                ('дата изменения', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=255)),
                ('fligth', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servise_classes', to='ahck.Flight')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Packet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('дата создания', models.DateTimeField(auto_now_add=True)),
                ('дата изменения', models.DateTimeField(auto_now=True)),
                ('barcode', models.CharField(default='', max_length=255, unique=True)),
                ('description_in_json', models.TextField(verbose_name='json packet description')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packets', to='ahck.Cargo')),
            ],
            options={
                'verbose_name': 'индивидуальный комплект',
                'verbose_name_plural': 'индивидуальные комплекты',
            },
        ),
        migrations.AddField(
            model_name='cargo',
            name='serviceclass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargos', to='ahck.ServiceClass'),
        ),
    ]
