# Generated by Django 2.2 on 2019-04-07 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ahck', '0003_auto_20190407_1009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actofshortage',
            old_name='flight',
            new_name='mock',
        ),
    ]
